
export const SET_XML_FILE = "SET_XML_FILE";
export const SET_SELECTED_STATE = "SET_SELECTED_STATE";
export const SET_STATES = "SET_STATES";
export const SET_CONDITIONS = "SET_CONDITIONS";
export const SET_UPLOAD_STATUS = "SET_UPLOAD_STATUS";
export const SET_FILE_LIST = "SET_FILE_LIST";
export const SET_SELECT_STATE_ENABLED = "SET_SELECT_STATE_ENABLED";
export const SET_CACHED_FILE_LIST = "SET_CACHED_FILE_LIST";
export const CACHE_PARSED_FILE = "CACHE_PARSED_FILE";